apiVersion: v1
kind: Service  # Service order service
metadata:
  name: order-service
  labels:
    app: order-service  # Label untuk order service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Port yang digunakan
      name: http