apiVersion: apps/v1
kind: Deployment  # Deployment order service
metadata:
  name: order-service # Nama dari deployment
  labels:
    app: order-service # Label untuk order service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true" # Set sidecar istio
    spec:
      containers:
      - name: order-service
        image: ghcr.io/ariellehug/a433-microservices/order-service:latest # Pull image dari github package
        ports:
        - containerPort: 3000
        env: 
        - name: PORT
          value: "3000"
        - name: AMQP_URL   # Untuk connect ke rabbitmq
          value: "amqp://user:MDXBXJZIfeGEQOsJ@rabbitmq.default.svc.cluster.local:5672"